---
# =============================================================================
# Ansible Playbook for Server Setup
# =============================================================================
# This playbook configures servers on AWS (EC2) or Hetzner
#
# Usage:
#   ./run-playbook.sh aws      # For AWS/EC2 instances
#   ./run-playbook.sh hetzner  # For Hetzner instances
#
# The playbook is organized into modular task files for maintainability:
#   - tasks/hetzner-root-setup.yaml  : Hetzner-specific volume & user setup
#   - tasks/common-packages.yaml     : System packages (both providers)
#   - tasks/common-dotfiles.yaml     : Dotfiles and git configuration
#   - tasks/common-tools.yaml        : Development tools (conda, nvim, etc.)
# =============================================================================

# -----------------------------------------------------------------------------
# Play 1: Hetzner Initial Setup (root user)
# -----------------------------------------------------------------------------
# This play only runs for Hetzner instances and must run as root.
# It handles:
#   - Mounting the persistent volume at /data
#   - Creating the ubuntu user with sudo access
#   - Copying SSH keys from root to ubuntu user
# -----------------------------------------------------------------------------
- name: Initial setup as root (Hetzner only)
  hosts: hetzner
  remote_user: root
  tasks:
    - name: Include Hetzner root setup tasks
      ansible.builtin.include_tasks:
        file: tasks/hetzner-root-setup.yaml

# -----------------------------------------------------------------------------
# Play 2: Main Setup (ubuntu user)
# -----------------------------------------------------------------------------
# This play runs for all hosts (both AWS and Hetzner) as the ubuntu user.
# -----------------------------------------------------------------------------
- name: Main setup tasks
  hosts: all
  remote_user: ubuntu
  environment:
    DOTFILES_FORCE: "true"
  tasks:
    - name: Include common package installation tasks
      ansible.builtin.include_tasks:
        file: tasks/common-packages.yaml

    - name: Include common dotfiles setup tasks
      ansible.builtin.include_tasks:
        file: tasks/common-dotfiles.yaml

  handlers:
    - name: Restart sshd
      become: true
      ansible.builtin.service:
        name: ssh
        state: restarted
