# Hetzner only, to make ubuntu user and mount volume in the correct location so
# it matches an equivalent AWS host.
- name: Initial setup as root (Hetzner only)
  hosts: hetzner
  remote_user: root
  tasks:
    - name: Include Hetzner root setup tasks
      ansible.builtin.include_tasks:
        file: tasks/hetzner-root-setup.yaml

- name: Common setup tasks
  hosts: all
  remote_user: ubuntu
  environment:
    DOTFILES_FORCE: "true"
  tasks:
    - name: Include common system configuration tasks
      ansible.builtin.include_tasks:
        file: tasks/common-system.yaml

    - name: Include common dotfiles setup tasks
      ansible.builtin.include_tasks:
        file: tasks/common-dotfiles.yaml

  handlers:
    - name: Restart sshd
      become: true
      ansible.builtin.service:
        name: ssh
        state: restarted
