#!/bin/bash

for i in recipes containers utils docs; do
  if [ ! -e ~/proj/bioconda-$i ]; then
    git clone git@github.com:bioconda/bioconda-$i ~/proj/bioconda-$i
  fi
done

if [ ! -e ~/proj/bioconda-utils/env ]; then
  (
    cd ~/proj/bioconda-utils
    conda create \
      -p ./env \
      -y \
      --file bioconda_utils/bioconda_utils-requirements.txt \
      --file test-requirements.txt
    eval "$(conda shell.bash hook 2> /dev/null)"
    conda activate ./env
    python -m pip install .
  )
fi
