#!/bin/bash

ID=$(cat .instance_id)
aws ec2 stop-instances --instance-ids $(cat .instance_id)
echo "Waiting until $ID is stopped..." 1>&2
aws ec2 wait instance-stopped --instance-ids $ID
echo "$ID stopped" 1>&2
